export const SET_DISCIPLINES = 'SET_DISCIPLINES';
export const SET_TEACHERS = 'SET_TEACHERS';
export const SET_GROUPS = 'SET_GROUPS';
export const SET_CLASSROOMS = 'SET_CLASSROOMS';
export const SET_LESSONS = 'SET_LESSONS';
export const SET_DAYS_OF_WEEK = 'SET_DAYS_OF_WEEK';
export const SET_SELECTED_GROUP_ID = 'SET_SELECTED_GROUP_ID';
